/* This is a generated file, edit the .stub.php file instead.
 * Stub hash: 8eb7038415b8e13c69a6c70f3d0773e68bfddbd3 */

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_SimdUtf_validate_utf8, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, string, IS_STRING, 0)
ZEND_END_ARG_INFO()

#define arginfo_SimdUtf_validate_ascii arginfo_SimdUtf_validate_utf8

#define arginfo_SimdUtf_validate_utf16 arginfo_SimdUtf_validate_utf8

#define arginfo_SimdUtf_validate_utf16be arginfo_SimdUtf_validate_utf8

#define arginfo_SimdUtf_validate_utf16le arginfo_SimdUtf_validate_utf8

#define arginfo_SimdUtf_validate_utf32 arginfo_SimdUtf_validate_utf8

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_SimdUtf_validate_utf8_with_errors, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, string, IS_STRING, 0)
ZEND_END_ARG_INFO()

#define arginfo_SimdUtf_validate_ascii_with_errors arginfo_SimdUtf_validate_utf8_with_errors

#define arginfo_SimdUtf_validate_utf16_with_errors arginfo_SimdUtf_validate_utf8_with_errors

#define arginfo_SimdUtf_validate_utf16be_with_errors arginfo_SimdUtf_validate_utf8_with_errors

#define arginfo_SimdUtf_validate_utf16le_with_errors arginfo_SimdUtf_validate_utf8_with_errors

#define arginfo_SimdUtf_validate_utf32_with_errors arginfo_SimdUtf_validate_utf8_with_errors

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_SimdUtf_count_utf8, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, string, IS_STRING, 0)
ZEND_END_ARG_INFO()

#define arginfo_SimdUtf_count_utf16 arginfo_SimdUtf_count_utf8

#define arginfo_SimdUtf_count_utf16be arginfo_SimdUtf_count_utf8

#define arginfo_SimdUtf_count_utf16le arginfo_SimdUtf_count_utf8

#define arginfo_SimdUtf_utf8_length_from_utf16 arginfo_SimdUtf_count_utf8

#define arginfo_SimdUtf_utf8_length_from_utf16be arginfo_SimdUtf_count_utf8

#define arginfo_SimdUtf_utf8_length_from_utf16le arginfo_SimdUtf_count_utf8

#define arginfo_SimdUtf_utf8_length_from_utf32 arginfo_SimdUtf_count_utf8

#define arginfo_SimdUtf_utf8_length_from_latin1 arginfo_SimdUtf_count_utf8

#define arginfo_SimdUtf_utf16_length_from_utf8 arginfo_SimdUtf_count_utf8

#define arginfo_SimdUtf_utf16_length_from_utf32 arginfo_SimdUtf_count_utf8

#define arginfo_SimdUtf_utf16_length_from_latin1 arginfo_SimdUtf_count_utf8

#define arginfo_SimdUtf_utf32_length_from_utf8 arginfo_SimdUtf_count_utf8

#define arginfo_SimdUtf_utf32_length_from_utf16 arginfo_SimdUtf_count_utf8

#define arginfo_SimdUtf_utf32_length_from_utf16be arginfo_SimdUtf_count_utf8

#define arginfo_SimdUtf_utf32_length_from_utf16le arginfo_SimdUtf_count_utf8

#define arginfo_SimdUtf_latin1_length_from_utf8 arginfo_SimdUtf_count_utf8

#define arginfo_SimdUtf_latin1_length_from_utf16 arginfo_SimdUtf_count_utf8

#define arginfo_SimdUtf_latin1_length_from_utf32 arginfo_SimdUtf_count_utf8

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_SimdUtf_convert_utf8_to_latin1, 0, 1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, string, IS_STRING, 0)
ZEND_END_ARG_INFO()

#define arginfo_SimdUtf_convert_utf8_to_utf16 arginfo_SimdUtf_convert_utf8_to_latin1

#define arginfo_SimdUtf_convert_utf8_to_utf16be arginfo_SimdUtf_convert_utf8_to_latin1

#define arginfo_SimdUtf_convert_utf8_to_utf16le arginfo_SimdUtf_convert_utf8_to_latin1

#define arginfo_SimdUtf_convert_utf8_to_utf32 arginfo_SimdUtf_convert_utf8_to_latin1

#define arginfo_SimdUtf_convert_utf16_to_utf8 arginfo_SimdUtf_convert_utf8_to_latin1

#define arginfo_SimdUtf_convert_utf16_to_latin1 arginfo_SimdUtf_convert_utf8_to_latin1

#define arginfo_SimdUtf_convert_utf16_to_utf32 arginfo_SimdUtf_convert_utf8_to_latin1

#define arginfo_SimdUtf_convert_utf16be_to_utf8 arginfo_SimdUtf_convert_utf8_to_latin1

#define arginfo_SimdUtf_convert_utf16be_to_utf32 arginfo_SimdUtf_convert_utf8_to_latin1

#define arginfo_SimdUtf_convert_utf16be_to_latin1 arginfo_SimdUtf_convert_utf8_to_latin1

#define arginfo_SimdUtf_convert_utf16le_to_utf8 arginfo_SimdUtf_convert_utf8_to_latin1

#define arginfo_SimdUtf_convert_utf16le_to_utf32 arginfo_SimdUtf_convert_utf8_to_latin1

#define arginfo_SimdUtf_convert_utf16le_to_latin1 arginfo_SimdUtf_convert_utf8_to_latin1

#define arginfo_SimdUtf_convert_utf32_to_utf8 arginfo_SimdUtf_convert_utf8_to_latin1

#define arginfo_SimdUtf_convert_utf32_to_utf16 arginfo_SimdUtf_convert_utf8_to_latin1

#define arginfo_SimdUtf_convert_utf32_to_utf16le arginfo_SimdUtf_convert_utf8_to_latin1

#define arginfo_SimdUtf_convert_utf32_to_utf16be arginfo_SimdUtf_convert_utf8_to_latin1

#define arginfo_SimdUtf_convert_utf32_to_latin1 arginfo_SimdUtf_convert_utf8_to_latin1

#define arginfo_SimdUtf_convert_latin1_to_utf8 arginfo_SimdUtf_convert_utf8_to_latin1

#define arginfo_SimdUtf_convert_latin1_to_utf16 arginfo_SimdUtf_convert_utf8_to_latin1

#define arginfo_SimdUtf_convert_latin1_to_utf16le arginfo_SimdUtf_convert_utf8_to_latin1

#define arginfo_SimdUtf_convert_latin1_to_utf16be arginfo_SimdUtf_convert_utf8_to_latin1

#define arginfo_SimdUtf_convert_latin1_to_utf32 arginfo_SimdUtf_convert_utf8_to_latin1

#define arginfo_SimdUtf_convert_utf8_to_utf16_with_errors arginfo_SimdUtf_validate_utf8_with_errors

#define arginfo_SimdUtf_convert_utf8_to_utf16be_with_errors arginfo_SimdUtf_validate_utf8_with_errors

#define arginfo_SimdUtf_convert_utf8_to_utf16le_with_errors arginfo_SimdUtf_validate_utf8_with_errors

#define arginfo_SimdUtf_convert_utf8_to_utf32_with_errors arginfo_SimdUtf_validate_utf8_with_errors

#define arginfo_SimdUtf_convert_utf8_to_latin1_with_errors arginfo_SimdUtf_validate_utf8_with_errors

#define arginfo_SimdUtf_convert_utf16_to_utf8_with_errors arginfo_SimdUtf_validate_utf8_with_errors

#define arginfo_SimdUtf_convert_utf16_to_utf32_with_errors arginfo_SimdUtf_validate_utf8_with_errors

#define arginfo_SimdUtf_convert_utf16_to_latin1_with_errors arginfo_SimdUtf_validate_utf8_with_errors

#define arginfo_SimdUtf_convert_utf16le_to_utf8_with_errors arginfo_SimdUtf_validate_utf8_with_errors

#define arginfo_SimdUtf_convert_utf16le_to_latin1_with_errors arginfo_SimdUtf_validate_utf8_with_errors

#define arginfo_SimdUtf_convert_utf16le_to_utf32_with_errors arginfo_SimdUtf_validate_utf8_with_errors

#define arginfo_SimdUtf_convert_utf16be_to_utf8_with_errors arginfo_SimdUtf_validate_utf8_with_errors

#define arginfo_SimdUtf_convert_utf16be_to_utf32_with_errors arginfo_SimdUtf_validate_utf8_with_errors

#define arginfo_SimdUtf_convert_utf16be_to_latin1_with_errors arginfo_SimdUtf_validate_utf8_with_errors

#define arginfo_SimdUtf_convert_utf32_to_utf8_with_errors arginfo_SimdUtf_validate_utf8_with_errors

#define arginfo_SimdUtf_convert_utf32_to_utf16_with_errors arginfo_SimdUtf_validate_utf8_with_errors

#define arginfo_SimdUtf_convert_utf32_to_utf16be_with_errors arginfo_SimdUtf_validate_utf8_with_errors

#define arginfo_SimdUtf_convert_utf32_to_utf16le_with_errors arginfo_SimdUtf_validate_utf8_with_errors

#define arginfo_SimdUtf_convert_utf32_to_latin1_with_errors arginfo_SimdUtf_validate_utf8_with_errors

#define arginfo_SimdUtf_convert_valid_utf8_to_latin1 arginfo_SimdUtf_convert_utf8_to_latin1

#define arginfo_SimdUtf_convert_valid_utf8_to_utf16 arginfo_SimdUtf_convert_utf8_to_latin1

#define arginfo_SimdUtf_convert_valid_utf8_to_utf16le arginfo_SimdUtf_convert_utf8_to_latin1

#define arginfo_SimdUtf_convert_valid_utf8_to_utf16be arginfo_SimdUtf_convert_utf8_to_latin1

#define arginfo_SimdUtf_convert_valid_utf8_to_utf32 arginfo_SimdUtf_convert_utf8_to_latin1

#define arginfo_SimdUtf_convert_valid_utf16_to_utf8 arginfo_SimdUtf_convert_utf8_to_latin1

#define arginfo_SimdUtf_convert_valid_utf16_to_latin1 arginfo_SimdUtf_convert_utf8_to_latin1

#define arginfo_SimdUtf_convert_valid_utf16_to_utf32 arginfo_SimdUtf_convert_utf8_to_latin1

#define arginfo_SimdUtf_convert_valid_utf16le_to_utf8 arginfo_SimdUtf_convert_utf8_to_latin1

#define arginfo_SimdUtf_convert_valid_utf16le_to_utf32 arginfo_SimdUtf_convert_utf8_to_latin1

#define arginfo_SimdUtf_convert_valid_utf16le_to_latin1 arginfo_SimdUtf_convert_utf8_to_latin1

#define arginfo_SimdUtf_convert_valid_utf16be_to_utf8 arginfo_SimdUtf_convert_utf8_to_latin1

#define arginfo_SimdUtf_convert_valid_utf16be_to_utf32 arginfo_SimdUtf_convert_utf8_to_latin1

#define arginfo_SimdUtf_convert_valid_utf16be_to_latin1 arginfo_SimdUtf_convert_utf8_to_latin1

#define arginfo_SimdUtf_convert_valid_utf32_to_latin1 arginfo_SimdUtf_convert_utf8_to_latin1

#define arginfo_SimdUtf_convert_valid_utf32_to_utf8 arginfo_SimdUtf_convert_utf8_to_latin1

#define arginfo_SimdUtf_convert_valid_utf32_to_utf16 arginfo_SimdUtf_convert_utf8_to_latin1

#define arginfo_SimdUtf_convert_valid_utf32_to_utf16be arginfo_SimdUtf_convert_utf8_to_latin1

#define arginfo_SimdUtf_convert_valid_utf32_to_utf16le arginfo_SimdUtf_convert_utf8_to_latin1

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_SimdUtf_change_endianness_utf16, 0, 2, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, string, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, length, IS_LONG, 0)
ZEND_END_ARG_INFO()

#define arginfo_SimdUtf_trim_partial_utf8 arginfo_SimdUtf_change_endianness_utf16

#define arginfo_SimdUtf_trim_partial_utf16be arginfo_SimdUtf_change_endianness_utf16

#define arginfo_SimdUtf_trim_partial_utf16le arginfo_SimdUtf_change_endianness_utf16

#define arginfo_SimdUtf_trim_partial_utf16 arginfo_SimdUtf_change_endianness_utf16

#define arginfo_SimdUtf_autodetect_encoding arginfo_SimdUtf_count_utf8

#define arginfo_SimdUtf_detect_encodings arginfo_SimdUtf_count_utf8

#define arginfo_SimdUtf_binary_to_base64 arginfo_SimdUtf_convert_utf8_to_latin1

#define arginfo_SimdUtf_base64_to_binary arginfo_SimdUtf_convert_utf8_to_latin1

#define arginfo_SimdUtf_base64_to_binary_safe arginfo_SimdUtf_convert_utf8_to_latin1


ZEND_FUNCTION(SimdUtf_validate_utf8);
ZEND_FUNCTION(SimdUtf_validate_ascii);
ZEND_FUNCTION(SimdUtf_validate_utf16);
ZEND_FUNCTION(SimdUtf_validate_utf16be);
ZEND_FUNCTION(SimdUtf_validate_utf16le);
ZEND_FUNCTION(SimdUtf_validate_utf32);
ZEND_FUNCTION(SimdUtf_validate_utf8_with_errors);
ZEND_FUNCTION(SimdUtf_validate_ascii_with_errors);
ZEND_FUNCTION(SimdUtf_validate_utf16_with_errors);
ZEND_FUNCTION(SimdUtf_validate_utf16be_with_errors);
ZEND_FUNCTION(SimdUtf_validate_utf16le_with_errors);
ZEND_FUNCTION(SimdUtf_validate_utf32_with_errors);
ZEND_FUNCTION(SimdUtf_count_utf8);
ZEND_FUNCTION(SimdUtf_count_utf16);
ZEND_FUNCTION(SimdUtf_count_utf16be);
ZEND_FUNCTION(SimdUtf_count_utf16le);
ZEND_FUNCTION(SimdUtf_utf8_length_from_utf16);
ZEND_FUNCTION(SimdUtf_utf8_length_from_utf16be);
ZEND_FUNCTION(SimdUtf_utf8_length_from_utf16le);
ZEND_FUNCTION(SimdUtf_utf8_length_from_utf32);
ZEND_FUNCTION(SimdUtf_utf8_length_from_latin1);
ZEND_FUNCTION(SimdUtf_utf16_length_from_utf8);
ZEND_FUNCTION(SimdUtf_utf16_length_from_utf32);
ZEND_FUNCTION(SimdUtf_utf16_length_from_latin1);
ZEND_FUNCTION(SimdUtf_utf32_length_from_utf8);
ZEND_FUNCTION(SimdUtf_utf32_length_from_utf16);
ZEND_FUNCTION(SimdUtf_utf32_length_from_utf16be);
ZEND_FUNCTION(SimdUtf_utf32_length_from_utf16le);
ZEND_FUNCTION(SimdUtf_latin1_length_from_utf8);
ZEND_FUNCTION(SimdUtf_latin1_length_from_utf16);
ZEND_FUNCTION(SimdUtf_latin1_length_from_utf32);
ZEND_FUNCTION(SimdUtf_convert_utf8_to_latin1);
ZEND_FUNCTION(SimdUtf_convert_utf8_to_utf16);
ZEND_FUNCTION(SimdUtf_convert_utf8_to_utf16be);
ZEND_FUNCTION(SimdUtf_convert_utf8_to_utf16le);
ZEND_FUNCTION(SimdUtf_convert_utf8_to_utf32);
ZEND_FUNCTION(SimdUtf_convert_utf16_to_utf8);
ZEND_FUNCTION(SimdUtf_convert_utf16_to_latin1);
ZEND_FUNCTION(SimdUtf_convert_utf16_to_utf32);
ZEND_FUNCTION(SimdUtf_convert_utf16be_to_utf8);
ZEND_FUNCTION(SimdUtf_convert_utf16be_to_utf32);
ZEND_FUNCTION(SimdUtf_convert_utf16be_to_latin1);
ZEND_FUNCTION(SimdUtf_convert_utf16le_to_utf8);
ZEND_FUNCTION(SimdUtf_convert_utf16le_to_utf32);
ZEND_FUNCTION(SimdUtf_convert_utf16le_to_latin1);
ZEND_FUNCTION(SimdUtf_convert_utf32_to_utf8);
ZEND_FUNCTION(SimdUtf_convert_utf32_to_utf16);
ZEND_FUNCTION(SimdUtf_convert_utf32_to_utf16le);
ZEND_FUNCTION(SimdUtf_convert_utf32_to_utf16be);
ZEND_FUNCTION(SimdUtf_convert_utf32_to_latin1);
ZEND_FUNCTION(SimdUtf_convert_latin1_to_utf8);
ZEND_FUNCTION(SimdUtf_convert_latin1_to_utf16);
ZEND_FUNCTION(SimdUtf_convert_latin1_to_utf16le);
ZEND_FUNCTION(SimdUtf_convert_latin1_to_utf16be);
ZEND_FUNCTION(SimdUtf_convert_latin1_to_utf32);
ZEND_FUNCTION(SimdUtf_convert_utf8_to_utf16_with_errors);
ZEND_FUNCTION(SimdUtf_convert_utf8_to_utf16be_with_errors);
ZEND_FUNCTION(SimdUtf_convert_utf8_to_utf16le_with_errors);
ZEND_FUNCTION(SimdUtf_convert_utf8_to_utf32_with_errors);
ZEND_FUNCTION(SimdUtf_convert_utf8_to_latin1_with_errors);
ZEND_FUNCTION(SimdUtf_convert_utf16_to_utf8_with_errors);
ZEND_FUNCTION(SimdUtf_convert_utf16_to_utf32_with_errors);
ZEND_FUNCTION(SimdUtf_convert_utf16_to_latin1_with_errors);
ZEND_FUNCTION(SimdUtf_convert_utf16le_to_utf8_with_errors);
ZEND_FUNCTION(SimdUtf_convert_utf16le_to_latin1_with_errors);
ZEND_FUNCTION(SimdUtf_convert_utf16le_to_utf32_with_errors);
ZEND_FUNCTION(SimdUtf_convert_utf16be_to_utf8_with_errors);
ZEND_FUNCTION(SimdUtf_convert_utf16be_to_utf32_with_errors);
ZEND_FUNCTION(SimdUtf_convert_utf16be_to_latin1_with_errors);
ZEND_FUNCTION(SimdUtf_convert_utf32_to_utf8_with_errors);
ZEND_FUNCTION(SimdUtf_convert_utf32_to_utf16_with_errors);
ZEND_FUNCTION(SimdUtf_convert_utf32_to_utf16be_with_errors);
ZEND_FUNCTION(SimdUtf_convert_utf32_to_utf16le_with_errors);
ZEND_FUNCTION(SimdUtf_convert_utf32_to_latin1_with_errors);
ZEND_FUNCTION(SimdUtf_convert_valid_utf8_to_latin1);
ZEND_FUNCTION(SimdUtf_convert_valid_utf8_to_utf16);
ZEND_FUNCTION(SimdUtf_convert_valid_utf8_to_utf16le);
ZEND_FUNCTION(SimdUtf_convert_valid_utf8_to_utf16be);
ZEND_FUNCTION(SimdUtf_convert_valid_utf8_to_utf32);
ZEND_FUNCTION(SimdUtf_convert_valid_utf16_to_utf8);
ZEND_FUNCTION(SimdUtf_convert_valid_utf16_to_latin1);
ZEND_FUNCTION(SimdUtf_convert_valid_utf16_to_utf32);
ZEND_FUNCTION(SimdUtf_convert_valid_utf16le_to_utf8);
ZEND_FUNCTION(SimdUtf_convert_valid_utf16le_to_utf32);
ZEND_FUNCTION(SimdUtf_convert_valid_utf16le_to_latin1);
ZEND_FUNCTION(SimdUtf_convert_valid_utf16be_to_utf8);
ZEND_FUNCTION(SimdUtf_convert_valid_utf16be_to_utf32);
ZEND_FUNCTION(SimdUtf_convert_valid_utf16be_to_latin1);
ZEND_FUNCTION(SimdUtf_convert_valid_utf32_to_latin1);
ZEND_FUNCTION(SimdUtf_convert_valid_utf32_to_utf8);
ZEND_FUNCTION(SimdUtf_convert_valid_utf32_to_utf16);
ZEND_FUNCTION(SimdUtf_convert_valid_utf32_to_utf16be);
ZEND_FUNCTION(SimdUtf_convert_valid_utf32_to_utf16le);
ZEND_FUNCTION(SimdUtf_change_endianness_utf16);
ZEND_FUNCTION(SimdUtf_trim_partial_utf8);
ZEND_FUNCTION(SimdUtf_trim_partial_utf16be);
ZEND_FUNCTION(SimdUtf_trim_partial_utf16le);
ZEND_FUNCTION(SimdUtf_trim_partial_utf16);
ZEND_FUNCTION(SimdUtf_autodetect_encoding);
ZEND_FUNCTION(SimdUtf_detect_encodings);
ZEND_FUNCTION(SimdUtf_binary_to_base64);
ZEND_FUNCTION(SimdUtf_base64_to_binary);
ZEND_FUNCTION(SimdUtf_base64_to_binary_safe);


static const zend_function_entry ext_functions[] = {
	ZEND_NS_FALIAS("SimdUtf", validate_utf8, SimdUtf_validate_utf8, arginfo_SimdUtf_validate_utf8)
	ZEND_NS_FALIAS("SimdUtf", validate_ascii, SimdUtf_validate_ascii, arginfo_SimdUtf_validate_ascii)
	ZEND_NS_FALIAS("SimdUtf", validate_utf16, SimdUtf_validate_utf16, arginfo_SimdUtf_validate_utf16)
	ZEND_NS_FALIAS("SimdUtf", validate_utf16be, SimdUtf_validate_utf16be, arginfo_SimdUtf_validate_utf16be)
	ZEND_NS_FALIAS("SimdUtf", validate_utf16le, SimdUtf_validate_utf16le, arginfo_SimdUtf_validate_utf16le)
	ZEND_NS_FALIAS("SimdUtf", validate_utf32, SimdUtf_validate_utf32, arginfo_SimdUtf_validate_utf32)
	ZEND_NS_FALIAS("SimdUtf", validate_utf8_with_errors, SimdUtf_validate_utf8_with_errors, arginfo_SimdUtf_validate_utf8_with_errors)
	ZEND_NS_FALIAS("SimdUtf", validate_ascii_with_errors, SimdUtf_validate_ascii_with_errors, arginfo_SimdUtf_validate_ascii_with_errors)
	ZEND_NS_FALIAS("SimdUtf", validate_utf16_with_errors, SimdUtf_validate_utf16_with_errors, arginfo_SimdUtf_validate_utf16_with_errors)
	ZEND_NS_FALIAS("SimdUtf", validate_utf16be_with_errors, SimdUtf_validate_utf16be_with_errors, arginfo_SimdUtf_validate_utf16be_with_errors)
	ZEND_NS_FALIAS("SimdUtf", validate_utf16le_with_errors, SimdUtf_validate_utf16le_with_errors, arginfo_SimdUtf_validate_utf16le_with_errors)
	ZEND_NS_FALIAS("SimdUtf", validate_utf32_with_errors, SimdUtf_validate_utf32_with_errors, arginfo_SimdUtf_validate_utf32_with_errors)
	ZEND_NS_FALIAS("SimdUtf", count_utf8, SimdUtf_count_utf8, arginfo_SimdUtf_count_utf8)
	ZEND_NS_FALIAS("SimdUtf", count_utf16, SimdUtf_count_utf16, arginfo_SimdUtf_count_utf16)
	ZEND_NS_FALIAS("SimdUtf", count_utf16be, SimdUtf_count_utf16be, arginfo_SimdUtf_count_utf16be)
	ZEND_NS_FALIAS("SimdUtf", count_utf16le, SimdUtf_count_utf16le, arginfo_SimdUtf_count_utf16le)
	ZEND_NS_FALIAS("SimdUtf", utf8_length_from_utf16, SimdUtf_utf8_length_from_utf16, arginfo_SimdUtf_utf8_length_from_utf16)
	ZEND_NS_FALIAS("SimdUtf", utf8_length_from_utf16be, SimdUtf_utf8_length_from_utf16be, arginfo_SimdUtf_utf8_length_from_utf16be)
	ZEND_NS_FALIAS("SimdUtf", utf8_length_from_utf16le, SimdUtf_utf8_length_from_utf16le, arginfo_SimdUtf_utf8_length_from_utf16le)
	ZEND_NS_FALIAS("SimdUtf", utf8_length_from_utf32, SimdUtf_utf8_length_from_utf32, arginfo_SimdUtf_utf8_length_from_utf32)
	ZEND_NS_FALIAS("SimdUtf", utf8_length_from_latin1, SimdUtf_utf8_length_from_latin1, arginfo_SimdUtf_utf8_length_from_latin1)
	ZEND_NS_FALIAS("SimdUtf", utf16_length_from_utf8, SimdUtf_utf16_length_from_utf8, arginfo_SimdUtf_utf16_length_from_utf8)
	ZEND_NS_FALIAS("SimdUtf", utf16_length_from_utf32, SimdUtf_utf16_length_from_utf32, arginfo_SimdUtf_utf16_length_from_utf32)
	ZEND_NS_FALIAS("SimdUtf", utf16_length_from_latin1, SimdUtf_utf16_length_from_latin1, arginfo_SimdUtf_utf16_length_from_latin1)
	ZEND_NS_FALIAS("SimdUtf", utf32_length_from_utf8, SimdUtf_utf32_length_from_utf8, arginfo_SimdUtf_utf32_length_from_utf8)
	ZEND_NS_FALIAS("SimdUtf", utf32_length_from_utf16, SimdUtf_utf32_length_from_utf16, arginfo_SimdUtf_utf32_length_from_utf16)
	ZEND_NS_FALIAS("SimdUtf", utf32_length_from_utf16be, SimdUtf_utf32_length_from_utf16be, arginfo_SimdUtf_utf32_length_from_utf16be)
	ZEND_NS_FALIAS("SimdUtf", utf32_length_from_utf16le, SimdUtf_utf32_length_from_utf16le, arginfo_SimdUtf_utf32_length_from_utf16le)
	ZEND_NS_FALIAS("SimdUtf", latin1_length_from_utf8, SimdUtf_latin1_length_from_utf8, arginfo_SimdUtf_latin1_length_from_utf8)
	ZEND_NS_FALIAS("SimdUtf", latin1_length_from_utf16, SimdUtf_latin1_length_from_utf16, arginfo_SimdUtf_latin1_length_from_utf16)
	ZEND_NS_FALIAS("SimdUtf", latin1_length_from_utf32, SimdUtf_latin1_length_from_utf32, arginfo_SimdUtf_latin1_length_from_utf32)
	ZEND_NS_FALIAS("SimdUtf", convert_utf8_to_latin1, SimdUtf_convert_utf8_to_latin1, arginfo_SimdUtf_convert_utf8_to_latin1)
	ZEND_NS_FALIAS("SimdUtf", convert_utf8_to_utf16, SimdUtf_convert_utf8_to_utf16, arginfo_SimdUtf_convert_utf8_to_utf16)
	ZEND_NS_FALIAS("SimdUtf", convert_utf8_to_utf16be, SimdUtf_convert_utf8_to_utf16be, arginfo_SimdUtf_convert_utf8_to_utf16be)
	ZEND_NS_FALIAS("SimdUtf", convert_utf8_to_utf16le, SimdUtf_convert_utf8_to_utf16le, arginfo_SimdUtf_convert_utf8_to_utf16le)
	ZEND_NS_FALIAS("SimdUtf", convert_utf8_to_utf32, SimdUtf_convert_utf8_to_utf32, arginfo_SimdUtf_convert_utf8_to_utf32)
	ZEND_NS_FALIAS("SimdUtf", convert_utf16_to_utf8, SimdUtf_convert_utf16_to_utf8, arginfo_SimdUtf_convert_utf16_to_utf8)
	ZEND_NS_FALIAS("SimdUtf", convert_utf16_to_latin1, SimdUtf_convert_utf16_to_latin1, arginfo_SimdUtf_convert_utf16_to_latin1)
	ZEND_NS_FALIAS("SimdUtf", convert_utf16_to_utf32, SimdUtf_convert_utf16_to_utf32, arginfo_SimdUtf_convert_utf16_to_utf32)
	ZEND_NS_FALIAS("SimdUtf", convert_utf16be_to_utf8, SimdUtf_convert_utf16be_to_utf8, arginfo_SimdUtf_convert_utf16be_to_utf8)
	ZEND_NS_FALIAS("SimdUtf", convert_utf16be_to_utf32, SimdUtf_convert_utf16be_to_utf32, arginfo_SimdUtf_convert_utf16be_to_utf32)
	ZEND_NS_FALIAS("SimdUtf", convert_utf16be_to_latin1, SimdUtf_convert_utf16be_to_latin1, arginfo_SimdUtf_convert_utf16be_to_latin1)
	ZEND_NS_FALIAS("SimdUtf", convert_utf16le_to_utf8, SimdUtf_convert_utf16le_to_utf8, arginfo_SimdUtf_convert_utf16le_to_utf8)
	ZEND_NS_FALIAS("SimdUtf", convert_utf16le_to_utf32, SimdUtf_convert_utf16le_to_utf32, arginfo_SimdUtf_convert_utf16le_to_utf32)
	ZEND_NS_FALIAS("SimdUtf", convert_utf16le_to_latin1, SimdUtf_convert_utf16le_to_latin1, arginfo_SimdUtf_convert_utf16le_to_latin1)
	ZEND_NS_FALIAS("SimdUtf", convert_utf32_to_utf8, SimdUtf_convert_utf32_to_utf8, arginfo_SimdUtf_convert_utf32_to_utf8)
	ZEND_NS_FALIAS("SimdUtf", convert_utf32_to_utf16, SimdUtf_convert_utf32_to_utf16, arginfo_SimdUtf_convert_utf32_to_utf16)
	ZEND_NS_FALIAS("SimdUtf", convert_utf32_to_utf16le, SimdUtf_convert_utf32_to_utf16le, arginfo_SimdUtf_convert_utf32_to_utf16le)
	ZEND_NS_FALIAS("SimdUtf", convert_utf32_to_utf16be, SimdUtf_convert_utf32_to_utf16be, arginfo_SimdUtf_convert_utf32_to_utf16be)
	ZEND_NS_FALIAS("SimdUtf", convert_utf32_to_latin1, SimdUtf_convert_utf32_to_latin1, arginfo_SimdUtf_convert_utf32_to_latin1)
	ZEND_NS_FALIAS("SimdUtf", convert_latin1_to_utf8, SimdUtf_convert_latin1_to_utf8, arginfo_SimdUtf_convert_latin1_to_utf8)
	ZEND_NS_FALIAS("SimdUtf", convert_latin1_to_utf16, SimdUtf_convert_latin1_to_utf16, arginfo_SimdUtf_convert_latin1_to_utf16)
	ZEND_NS_FALIAS("SimdUtf", convert_latin1_to_utf16le, SimdUtf_convert_latin1_to_utf16le, arginfo_SimdUtf_convert_latin1_to_utf16le)
	ZEND_NS_FALIAS("SimdUtf", convert_latin1_to_utf16be, SimdUtf_convert_latin1_to_utf16be, arginfo_SimdUtf_convert_latin1_to_utf16be)
	ZEND_NS_FALIAS("SimdUtf", convert_latin1_to_utf32, SimdUtf_convert_latin1_to_utf32, arginfo_SimdUtf_convert_latin1_to_utf32)
	ZEND_NS_FALIAS("SimdUtf", convert_utf8_to_utf16_with_errors, SimdUtf_convert_utf8_to_utf16_with_errors, arginfo_SimdUtf_convert_utf8_to_utf16_with_errors)
	ZEND_NS_FALIAS("SimdUtf", convert_utf8_to_utf16be_with_errors, SimdUtf_convert_utf8_to_utf16be_with_errors, arginfo_SimdUtf_convert_utf8_to_utf16be_with_errors)
	ZEND_NS_FALIAS("SimdUtf", convert_utf8_to_utf16le_with_errors, SimdUtf_convert_utf8_to_utf16le_with_errors, arginfo_SimdUtf_convert_utf8_to_utf16le_with_errors)
	ZEND_NS_FALIAS("SimdUtf", convert_utf8_to_utf32_with_errors, SimdUtf_convert_utf8_to_utf32_with_errors, arginfo_SimdUtf_convert_utf8_to_utf32_with_errors)
	ZEND_NS_FALIAS("SimdUtf", convert_utf8_to_latin1_with_errors, SimdUtf_convert_utf8_to_latin1_with_errors, arginfo_SimdUtf_convert_utf8_to_latin1_with_errors)
	ZEND_NS_FALIAS("SimdUtf", convert_utf16_to_utf8_with_errors, SimdUtf_convert_utf16_to_utf8_with_errors, arginfo_SimdUtf_convert_utf16_to_utf8_with_errors)
	ZEND_NS_FALIAS("SimdUtf", convert_utf16_to_utf32_with_errors, SimdUtf_convert_utf16_to_utf32_with_errors, arginfo_SimdUtf_convert_utf16_to_utf32_with_errors)
	ZEND_NS_FALIAS("SimdUtf", convert_utf16_to_latin1_with_errors, SimdUtf_convert_utf16_to_latin1_with_errors, arginfo_SimdUtf_convert_utf16_to_latin1_with_errors)
	ZEND_NS_FALIAS("SimdUtf", convert_utf16le_to_utf8_with_errors, SimdUtf_convert_utf16le_to_utf8_with_errors, arginfo_SimdUtf_convert_utf16le_to_utf8_with_errors)
	ZEND_NS_FALIAS("SimdUtf", convert_utf16le_to_latin1_with_errors, SimdUtf_convert_utf16le_to_latin1_with_errors, arginfo_SimdUtf_convert_utf16le_to_latin1_with_errors)
	ZEND_NS_FALIAS("SimdUtf", convert_utf16le_to_utf32_with_errors, SimdUtf_convert_utf16le_to_utf32_with_errors, arginfo_SimdUtf_convert_utf16le_to_utf32_with_errors)
	ZEND_NS_FALIAS("SimdUtf", convert_utf16be_to_utf8_with_errors, SimdUtf_convert_utf16be_to_utf8_with_errors, arginfo_SimdUtf_convert_utf16be_to_utf8_with_errors)
	ZEND_NS_FALIAS("SimdUtf", convert_utf16be_to_utf32_with_errors, SimdUtf_convert_utf16be_to_utf32_with_errors, arginfo_SimdUtf_convert_utf16be_to_utf32_with_errors)
	ZEND_NS_FALIAS("SimdUtf", convert_utf16be_to_latin1_with_errors, SimdUtf_convert_utf16be_to_latin1_with_errors, arginfo_SimdUtf_convert_utf16be_to_latin1_with_errors)
	ZEND_NS_FALIAS("SimdUtf", convert_utf32_to_utf8_with_errors, SimdUtf_convert_utf32_to_utf8_with_errors, arginfo_SimdUtf_convert_utf32_to_utf8_with_errors)
	ZEND_NS_FALIAS("SimdUtf", convert_utf32_to_utf16_with_errors, SimdUtf_convert_utf32_to_utf16_with_errors, arginfo_SimdUtf_convert_utf32_to_utf16_with_errors)
	ZEND_NS_FALIAS("SimdUtf", convert_utf32_to_utf16be_with_errors, SimdUtf_convert_utf32_to_utf16be_with_errors, arginfo_SimdUtf_convert_utf32_to_utf16be_with_errors)
	ZEND_NS_FALIAS("SimdUtf", convert_utf32_to_utf16le_with_errors, SimdUtf_convert_utf32_to_utf16le_with_errors, arginfo_SimdUtf_convert_utf32_to_utf16le_with_errors)
	ZEND_NS_FALIAS("SimdUtf", convert_utf32_to_latin1_with_errors, SimdUtf_convert_utf32_to_latin1_with_errors, arginfo_SimdUtf_convert_utf32_to_latin1_with_errors)
	ZEND_NS_FALIAS("SimdUtf", convert_valid_utf8_to_latin1, SimdUtf_convert_valid_utf8_to_latin1, arginfo_SimdUtf_convert_valid_utf8_to_latin1)
	ZEND_NS_FALIAS("SimdUtf", convert_valid_utf8_to_utf16, SimdUtf_convert_valid_utf8_to_utf16, arginfo_SimdUtf_convert_valid_utf8_to_utf16)
	ZEND_NS_FALIAS("SimdUtf", convert_valid_utf8_to_utf16le, SimdUtf_convert_valid_utf8_to_utf16le, arginfo_SimdUtf_convert_valid_utf8_to_utf16le)
	ZEND_NS_FALIAS("SimdUtf", convert_valid_utf8_to_utf16be, SimdUtf_convert_valid_utf8_to_utf16be, arginfo_SimdUtf_convert_valid_utf8_to_utf16be)
	ZEND_NS_FALIAS("SimdUtf", convert_valid_utf8_to_utf32, SimdUtf_convert_valid_utf8_to_utf32, arginfo_SimdUtf_convert_valid_utf8_to_utf32)
	ZEND_NS_FALIAS("SimdUtf", convert_valid_utf16_to_utf8, SimdUtf_convert_valid_utf16_to_utf8, arginfo_SimdUtf_convert_valid_utf16_to_utf8)
	ZEND_NS_FALIAS("SimdUtf", convert_valid_utf16_to_latin1, SimdUtf_convert_valid_utf16_to_latin1, arginfo_SimdUtf_convert_valid_utf16_to_latin1)
	ZEND_NS_FALIAS("SimdUtf", convert_valid_utf16_to_utf32, SimdUtf_convert_valid_utf16_to_utf32, arginfo_SimdUtf_convert_valid_utf16_to_utf32)
	ZEND_NS_FALIAS("SimdUtf", convert_valid_utf16le_to_utf8, SimdUtf_convert_valid_utf16le_to_utf8, arginfo_SimdUtf_convert_valid_utf16le_to_utf8)
	ZEND_NS_FALIAS("SimdUtf", convert_valid_utf16le_to_utf32, SimdUtf_convert_valid_utf16le_to_utf32, arginfo_SimdUtf_convert_valid_utf16le_to_utf32)
	ZEND_NS_FALIAS("SimdUtf", convert_valid_utf16le_to_latin1, SimdUtf_convert_valid_utf16le_to_latin1, arginfo_SimdUtf_convert_valid_utf16le_to_latin1)
	ZEND_NS_FALIAS("SimdUtf", convert_valid_utf16be_to_utf8, SimdUtf_convert_valid_utf16be_to_utf8, arginfo_SimdUtf_convert_valid_utf16be_to_utf8)
	ZEND_NS_FALIAS("SimdUtf", convert_valid_utf16be_to_utf32, SimdUtf_convert_valid_utf16be_to_utf32, arginfo_SimdUtf_convert_valid_utf16be_to_utf32)
	ZEND_NS_FALIAS("SimdUtf", convert_valid_utf16be_to_latin1, SimdUtf_convert_valid_utf16be_to_latin1, arginfo_SimdUtf_convert_valid_utf16be_to_latin1)
	ZEND_NS_FALIAS("SimdUtf", convert_valid_utf32_to_latin1, SimdUtf_convert_valid_utf32_to_latin1, arginfo_SimdUtf_convert_valid_utf32_to_latin1)
	ZEND_NS_FALIAS("SimdUtf", convert_valid_utf32_to_utf8, SimdUtf_convert_valid_utf32_to_utf8, arginfo_SimdUtf_convert_valid_utf32_to_utf8)
	ZEND_NS_FALIAS("SimdUtf", convert_valid_utf32_to_utf16, SimdUtf_convert_valid_utf32_to_utf16, arginfo_SimdUtf_convert_valid_utf32_to_utf16)
	ZEND_NS_FALIAS("SimdUtf", convert_valid_utf32_to_utf16be, SimdUtf_convert_valid_utf32_to_utf16be, arginfo_SimdUtf_convert_valid_utf32_to_utf16be)
	ZEND_NS_FALIAS("SimdUtf", convert_valid_utf32_to_utf16le, SimdUtf_convert_valid_utf32_to_utf16le, arginfo_SimdUtf_convert_valid_utf32_to_utf16le)
	ZEND_NS_FALIAS("SimdUtf", change_endianness_utf16, SimdUtf_change_endianness_utf16, arginfo_SimdUtf_change_endianness_utf16)
	ZEND_NS_FALIAS("SimdUtf", trim_partial_utf8, SimdUtf_trim_partial_utf8, arginfo_SimdUtf_trim_partial_utf8)
	ZEND_NS_FALIAS("SimdUtf", trim_partial_utf16be, SimdUtf_trim_partial_utf16be, arginfo_SimdUtf_trim_partial_utf16be)
	ZEND_NS_FALIAS("SimdUtf", trim_partial_utf16le, SimdUtf_trim_partial_utf16le, arginfo_SimdUtf_trim_partial_utf16le)
	ZEND_NS_FALIAS("SimdUtf", trim_partial_utf16, SimdUtf_trim_partial_utf16, arginfo_SimdUtf_trim_partial_utf16)
	ZEND_NS_FALIAS("SimdUtf", autodetect_encoding, SimdUtf_autodetect_encoding, arginfo_SimdUtf_autodetect_encoding)
	ZEND_NS_FALIAS("SimdUtf", detect_encodings, SimdUtf_detect_encodings, arginfo_SimdUtf_detect_encodings)
	ZEND_NS_FALIAS("SimdUtf", binary_to_base64, SimdUtf_binary_to_base64, arginfo_SimdUtf_binary_to_base64)
	ZEND_NS_FALIAS("SimdUtf", base64_to_binary, SimdUtf_base64_to_binary, arginfo_SimdUtf_base64_to_binary)
	ZEND_NS_FALIAS("SimdUtf", base64_to_binary_safe, SimdUtf_base64_to_binary_safe, arginfo_SimdUtf_base64_to_binary_safe)
	ZEND_FE_END
};
